### ISSUE TITLE
题目难度

### ISSUE THREAD

**Issue by zx3xyy** [cai-lw/cs-97si-solutions#1]
这套题目难度是什么样的哦 -- 是leetcode hard吗

**Comment by cai-lw** [comment]
这门课是面向算法竞赛的，单纯为准备找工作刷题的话不建议刷
个人感觉Leetcode hard相当于这套题的5到6级

**Comment by zx3xyy** [comment]
是哦好多network flow的题感觉找工作用不到 = =
